# Generated by Django 2.1.4 on 2019-01-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtracks',
            name='track_obj',
            field=models.FileField(default='', upload_to='audio/'),
        ),
    ]
