# Generated by Django 2.1.4 on 2019-01-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190108_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtracks',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
